sudo: required
dist: trusty
language: node_js
node_js:
  - '7'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install -g pkg
- npm install -g apidoc
- npm install -g jasmine
- npm install -g protractor
- npm install --prefix front
- npm install --prefix back

cache:
  directories:
    - "node_modules"
    - "front/node_modules"
    - "back/node_modules"
    - "builds"

jobs:
  include:
    - stage: test-ui
      script: npm run test:ci --prefix front
    # - stage: test-service
    #   script: npm run test --prefix back
    # - stage: test-e2e
    #   script: npm run test:e2e --prefix front
    # - stage: build
    #   script: npm run build:prod --prefix back
